return {
  {
    "vague2k/huez.nvim",
    branch = "stable",
    event = "UIEnter",
    dependencies = {
      {
        "catppuccin/nvim",
        name = "catppuccin",
        opts = {
          no_underline = true,
          show_end_of_buffer = true,
        },
      },
      "rebelot/kanagawa.nvim",
      "Mofiqul/dracula.nvim",
      "folke/tokyonight.nvim",
      "Mofiqul/vscode.nvim",
      "bluz71/vim-moonfly-colors",
      "tiagovla/tokyodark.nvim",
      "navarasu/onedark.nvim",
      "eldritch-theme/eldritch.nvim",
    },
    opts = {
      file_path = vim.fs.normalize("~/.nvim.huez.lua"),
      fallback = "retrobox",
      omit = {
        "desert",
        "evening",
        "industry",
        "koehler",
        "morning",
        "murphy",
        "pablo",
        "peachpuff",
        "ron",
        "shine",
        "slate",
        "torte",
        "zellner",
        "blue",
        "darkblue",
        "delek",
        "quiet",
        "elflord",
        "lunaperche",
        "sorbet",
        "vim",
        "wildcharm",
        "zaibatsu",
        "minicyan",
        "minischeme",
        "randomhue",
      },
    },
    keys = {
      { "<leader>uC", "<cmd>Huez<cr>", desc = "Select colorscheme" },
    },
  },
  {
    "nvim-telescope/telescope.nvim",
    keys = {
      { "<leader>uC", false },
    },
  },
}
