return {
  -- {
  --   "nvim-treesitter/nvim-treesitter",
  --   opts = {
  --     textObjects = {
  --       select = {
  --         enable = true,
  --         lookahead = true,
  --         keymaps = {
  --           ["af"] = "@function.outer",
  --           ["if"] = "@function.inner",
  --           ["ac"] = "@class.outer",
  --           ["ic"] = "@class.inner",
  --           ["ia"] = "@parameter.inner",
  --         },
  --       },
  --       swap = {
  --         enable = true,
  --         swap_next = {
  --           ["<leader>a"] = "@parameter.inner",
  --         },
  --         swap_previous = {
  --           ["<leader>A"] = "@parameter.inner",
  --         },
  --       },
  --       move = {
  --         enable = true,
  --         set_jumps = true,
  --         goto_next_start = {
  --           ["]m"] = "@function.outer",
  --           ["]c"] = "@class.outer",
  --           ["]a"] = "@parameter.inner",
  --         },
  --       },
  --     },
  --   },
  -- },
}
